services:
  - type: web
    name: kitty-webhook
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python webhook_server.py
    build:
      environment:
        pythonVersion: 3.11.9
