services:
  - type: web
    name: kitty-webhook2
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python webhook_server.py"
    pythonVersion: 3.11
