prebuilds:
  enabled: false
services:
  - type: web
    name: kitty-webhook2
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python webhook_server.py"
    envVars:
      - key: PORT
        value: 5000
    pythonVersion: "3.11"
